version/urls.py
from django.conf.urls import url
from .views import (
    ContactView,
    ContactDoneView,
    file_download,
    ChangeList,
    VersionFilesView,
    VersionList,
)

urlpatterns = [
    url(r'^changes/$', ChangeList.as_view(), name='change-list'),
    url(r'^contact/$', ContactView.as_view(), name='contact'),
    url(r'^contact/done/$', ContactDoneView.as_view(), name='contact-done'),
    url(r'^file/(?P<pk>\d+)/$', file_download, name='file-download'),
    url(r'^version/$', VersionList.as_view(), name='version-list'),
    url(r'^version/files/(?P<pk>\d+)/$', VersionFilesView.as_view(), name='version-files'),
]

versionSystem/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic.base import RedirectView
import django.views.static

from accounts.views import (
    LoginView,
    LogoutView,
)


urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^', include('version.urls', namespace='version')),
    url(r'^$', RedirectView.as_view(url=reverse_lazy('version:version-list'), permanent=False)),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += [
        url(r'^static/(.*)$', django.views.static.serve, {'document_root': settings.STATIC_ROOT}),
        url(r'^media/(.*)$', django.views.static.serve, {'document_root': settings.MEDIA_ROOT}),
        url(r'^robots.txt', lambda x: HttpResponse("User-Agent: *\nDisallow: /", content_type="text/plain"), name="robots_file"),
    ]

version/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from django.utils.translation import ugettext_lazy as _
import os
from re import search
from shutil import rmtree


def file_directory_path(instance, filename):
    return 'version_{0}/{1}'.format(instance.version.id, filename)


class Client(models.Model):
    client_name = models.CharField(max_length=100, unique=True)
    ein = models.CharField(_('EIN'), max_length=50, unique=True)
    city = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=15)
    street = models.CharField(max_length=150)
    country = models.CharField(max_length=80, default=settings.DEFAULT_COUNTRY)
    phone_number = models.CharField(max_length=15, blank=True)
    sec_level = models.PositiveSmallIntegerField(default=0)
    license_number = models.CharField(max_length=15)
    license_date = models.DateField(auto_now=True, auto_now_add=False)
    expiration_version_date = models.DateField(auto_now=False, auto_now_add=False)
    expiration_changes_date = models.DateField(auto_now=False, auto_now_add=False)

    def __unicode__(self):
        return self.client_name

    def get_address(self):
        return unicode(self.street + ', ' + self.zipcode + ' ' + self.city)


class Version(models.Model):
    version = models.CharField(max_length=15)
    version_date = models.DateField(auto_now=False, auto_now_add=False)
    description = models.TextField(blank=True)
    clients = models.ManyToManyField(Client, blank=True)

    class Meta:
        ordering = ['-id']

    def __unicode__(self):
        return self.version

    def save(self, *args, **kwargs):
        self.version = self.version.replace(',', '.')
        super(Version, self).save(*args, **kwargs)

    def get_clients(self):
        return self.clients.all()

    def get_files(self):
        return self.files.all()


class File(models.Model):
    filename = models.CharField(max_length=50, blank=True)
    file = models.FileField(upload_to=file_directory_path)
    version = models.ForeignKey(Version, related_name='files', on_delete=models.CASCADE)

    class Meta:
        ordering = ['-version']

    def __unicode__(self):
        return self.filename

    def save(self, *args, **kwargs):
        super(File, self).save(*args, **kwargs)
        if not self.filename:
            new_filename = search(r'version_\d+/(.+)', self.file.name).group(1)
            file_obj = File.objects.filter(id=self.id).update(filename=new_filename)
            return file_obj


class Change(models.Model):
    CHANGE_TYPE_CHOICES = (
        (0, 'News'),
        (1, 'Bug'),
        (9, 'Release'),
    )
    change_type = models.PositiveSmallIntegerField(choices=CHANGE_TYPE_CHOICES, default=0)
    date = models.DateField(auto_now=False, auto_now_add=False)
    sec_level = models.PositiveSmallIntegerField(default=0)
    version = models.CharField(max_length=10)
    description = models.TextField()
    client = models.ForeignKey(Client, related_name='changes', null=True, blank=True)

    class Meta:
        ordering = ['-id']

    def __unicode__(self):
        return unicode(self.id)


class Loggs(models.Model):
    DB_TABLE_CHOICES = (
        ('version_file','version_file'),
    )
    logg_date = models.DateTimeField(auto_now=True, auto_now_add=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='loggs')
    db_table = models.CharField(_('db_table'), max_length=50, choices=DB_TABLE_CHOICES)
    record_id = models.PositiveIntegerField(_('record_id'))

    class Meta:
        verbose_name = 'logg'
        verbose_name_plural = 'loggs'
        ordering = ['-id']


@receiver(pre_delete, sender=Version)
def all_files_delete(sender, instance, **kwargs):
    if os.path.isdir('media/version_%d/' % instance.id):
        rmtree('media/version_%d/' % instance.id)


@receiver(pre_delete, sender=File)
def file_delete(sender, instance, **kwargs):
    instance.file.delete(False)

version/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from django.conf import settings
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.translation import ugettext_lazy as _

from .models import (
    Change,
    Version,
)


class ContactForm(forms.Form):
    TOPIC_CHOICES = (
        (_("Version"), _("Version")),
        (_("Changes"), _("Changes")),
        (_("Other"), _("Other")),
    )
    topic = forms.ChoiceField(choices=TOPIC_CHOICES, widget=forms.Select(attrs={
        'id': 'topic',
        'class':'form-control form'})
    )
    topic_version = forms.ModelChoiceField(
        label = 'Choose version',
        queryset = Version.objects.all().values_list('id', flat=True),
        widget = forms.Select(attrs={
            'class':'form-control form topic_version',
        }),
        required = False,
    )
    topic_change = forms.CharField(required=False)
    topic_custom = forms.CharField(required=False)
    name = forms.CharField()
    email = forms.EmailField()
    phone_number = forms.CharField(required=False)
    message = forms.CharField(widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['topic_change'].widget = forms.TextInput(attrs={
            'class': 'form-control form topic_change',
            'type': 'text',
            'placeholder': 'Change ID'})
        self.fields['topic_custom'].widget = forms.TextInput(attrs={
            'class': 'form-control form topic_custom',
            'type': 'text',
            'placeholder': 'Topic'})
        self.fields['name'].widget = forms.TextInput(attrs={
            'class': 'form-control form',
            'type': 'text',
            'placeholder': 'Name *'})
        self.fields['email'].widget = forms.TextInput(attrs={
            'class': 'form-control form',
            'type': 'email',
            'placeholder': 'E-mail *'})
        self.fields['phone_number'].widget = forms.TextInput(attrs={
            'class': 'form-control form',
            'type': 'text',
            'placeholder': 'Phone number'})
        self.fields['message'].widget = forms.Textarea(attrs={
            'class': 'form-control form textarea',
            'type': 'text',
            'contentEditable': 'true',
            'placeholder': 'Message *'})

    def send_email(self):
        msg_html = render_to_string('version/contact_email.html', {
            'name': self.cleaned_data['name'],
            'email': self.cleaned_data['email'],
            'phone_number': self.cleaned_data['phone_number'],
            'topic': self.cleaned_data['topic'],
            'topic_version': self.cleaned_data['topic_version'],
            'topic_change': self.cleaned_data['topic_change'],
            'topic_custom': self.cleaned_data['topic_custom'],
            'message': self.cleaned_data['message'],
        })

        subject = "Version System: e-mail from " + self.cleaned_data['name']
        from_email = settings.DEFAULT_FROM_EMAIL
        to_mail = settings.EMAIL_TO
        new_email = send_mail(
            subject,
            msg_html,
            from_email,
            to_mail,
            html_message=msg_html,
            fail_silently=False
        )
        return subject

version/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from datetime import date
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin,
)
from django.core.signals import request_finished
from django.db.models import Q
from django.dispatch import receiver
from django.http import (
    Http404,
    HttpResponse,
)
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import (
    FormView,
    ListView,
    TemplateView,
)
import os
import operator
from re import match
from shutil import (
    make_archive, 
    rmtree,
)

from .forms import (
    ContactForm,
)
from .models import (
    Change,
    Client,
    File,
    Loggs,
    Version,
)


class ExpirationVersionMixin(UserPassesTestMixin):
    raise_exception = True
    permission_denied_message = 'Your license expired. In order to continue to use this \
                                functionality, please purchase a new license.'

    def test_func(self):
        if not self.request.user.is_staff:
            if not self.request.user.client is None:
                return self.request.user.client.expiration_version_date >= date.today()
            else:
                return False
        else:
            return True


class ExpirationChangesMixin(UserPassesTestMixin):
    raise_exception = True
    permission_denied_message = 'Your license expired. In order to continue to use this \
                                functionality, please purchase a new license.'
                                
    def test_func(self):
        if not self.request.user.is_staff:
            if not self.request.user.client is None:
                return self.request.user.client.expiration_changes_date >= date.today()
            else:
                return False
        else:
            return True


class ContactView(FormView):
    form_class = ContactForm
    template_name = 'version/contact.html'
    success_url = reverse_lazy('version:contact-done')

    def get_initial(self):
        initial = super(ContactView, self).get_initial()
        if self.request.user.is_authenticated():
            first_name = self.request.user.first_name
            last_name = self.request.user.last_name
            if first_name and last_name:
                initial['name'] = first_name + ' ' + last_name
            initial['email'] = self.request.user.email
        return initial

    def form_valid(self, form):
        form.send_email()
        return super(ContactView, self).form_valid(form)


class ContactDoneView(TemplateView):
    template_name = 'version/contact_done.html'


class ChangeList(LoginRequiredMixin, ExpirationChangesMixin, ListView):
    model = Change
    context_object_name = "changes"
    paginate_by = 10
    allow_empty = True

    def get_queryset(self):
        change_obj = Change.objects.all()
        try:
            is_staff = self.request.user.is_staff
            if not is_staff:
                client_id = self.request.user.client.id
                client_obj = Client.objects.get(id=client_id)
                change_obj = change_obj.filter(
                    sec_level__lte = client_obj.sec_level
                )
        except:
            change_obj = change_obj.none()

        query = self.request.GET.get('q')
        if query:
            if match(r'^\d+,\d+$', query):
                query = query.replace(',', '.')
            query_list = query.split()
            change_obj = change_obj.filter(
                reduce(operator.or_,
                       (Q(id__contains=q) for q in query_list)) |
                reduce(operator.or_,
                       (Q(change_type__contains=q) for q in query_list)) |
                reduce(operator.or_,
                       (Q(date__icontains=q) for q in query_list)) |
                reduce(operator.or_,
                       (Q(version__icontains=q) for q in query_list)) |
                reduce(operator.or_,
                       (Q(description__icontains=q) for q in query_list)) |
                reduce(operator.or_,
                       (Q(client__client_name__icontains=q) for q in query_list))
            )

        date_from = self.request.GET.get('date_from')
        date_to = self.request.GET.get('date_to')
        if date_from or date_to:
            try:
                change_obj = change_obj.filter(
                    date__range = [date_from, date_to]
                )
            except:
                change_obj = change_obj.none()
        return change_obj

    def get_context_data(self, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)
        context['paginated_by'] = self.paginate_by
        query = self.request.GET.get('q')
        if query:
            context['q'] = query
        date_from = self.request.GET.get('date_from')
        if date_from:
            context['date_from'] = date_from
        date_to = self.request.GET.get('date_to')
        if date_to:
            context['date_to'] = date_to
        return context

    def get_paginate_by(self, queryset):
        pagination = self.request.COOKIES.get('change_paginated_by', '')
        if pagination:
            self.paginate_by = pagination
        return self.paginate_by


class VersionList(LoginRequiredMixin, ExpirationVersionMixin, ListView):
    model = Version
    context_object_name = "versions"
    paginate_by = 10
    allow_empty = True

    def get_queryset(self):
        is_staff = self.request.user.is_staff
        if is_staff:
            version_obj = Version.objects.all()
        else:
            version_obj = Version.objects.filter(clients=self.request.user.client).all()

        ordering = self.request.GET.get('ordering', '-id')
        if ordering:
            version_obj = version_obj.order_by(ordering)
        
        query = self.request.GET.get('q')
        if query:
            if match(r'^\d+,\d+$', query):
                query = query.replace(',', '.')
            query_list = query.split()
            version_obj = version_obj.filter(
                reduce(operator.and_,
                       (Q(version__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(description__icontains=q) for q in query_list))
            )
        return version_obj
    
    def get_context_data(self, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)
        context['paginated_by'] = self.paginate_by
        context['ordering'] = self.request.GET.get('ordering', '-id')
        query = self.request.GET.get('q')
        if query:
            context['q'] = self.request.GET.get('q')
        return context

    def get_paginate_by(self, queryset):
        pagination = self.request.COOKIES.get('version_paginated_by', '')
        if pagination:
            self.paginate_by = pagination
        return self.paginate_by


def file_download(request, pk):
    try:
        file = File.objects.get(id=pk)
        logger = Loggs(
            user = request.user,
            db_table = 'version_file',
            record_id = file.id,
        )
        logger.save()
    except File.DoesNotExist:
        raise Http404('File not found')
    return redirect(file.file.url)


class VersionFilesView(LoginRequiredMixin, ExpirationVersionMixin, View):
    @receiver(request_finished, sender=Version)
    def get(self, request, *args, **kwargs):
        version_id = self.kwargs['pk']
        
        dir_name = 'media/version_' + version_id
        output_filename = 'media/tmp/version_' + version_id
        make_archive(output_filename, 'zip', dir_name)
        file_path = output_filename + '.zip'
        zip_file = open(file_path, 'r')
        response = HttpResponse(zip_file, content_type='application/zip')
        response['Content-Disposition'] = 'attachment; filename=version_%s.zip' % version_id

        for file_obj in File.objects.filter(version=version_id):
            logger = Loggs(
            user = request.user,
            db_table = 'version_file',
            record_id = file_obj.id,
            )
            logger.save()
        return response


@receiver(request_finished)
def zip_files(sender, **kwargs):
    if os.path.isdir('media/tmp/'):
        rmtree('media/tmp/')

templates/version/change_list.html
{% extends "base.html" %}
{% block content %}
{% load bootstrap_pagination %}

<script type="text/javascript">
    $(document).ready(function() {
        var today = new Date();
        var expiry = new Date(today.getTime() + 365 * 24 * 3600 * 1000);

        function setCookie(name, value) {
            document.cookie=name + "=" + escape(value) + "; path=/; expires=" + expiry.toGMTString();
        };
        function putCookie() {
            setCookie("change_paginated_by", $("input[name=paginated_by]").val());
            return true;
        };
        function change_pagination() { 
            setTimeout( function() {
                putCookie();
                location.reload();
            }, 2000);
        };
        $('#paginated_by').on('change keyup paste click', change_pagination);

        $('#change').html($('#change').html().replace(/(https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9]\.[^\s]{2,})/gi, '<a href="$1" target="_blank" rel="nofollow">$1</a>'));
        
        $(".datepicker").datepicker({ dateFormat: 'yy-mm-dd' });

        var q = $("#q").val();
        if(q.length > 0) {
            var word = q.match(/\S+/g);
            var arrayLength = word.length;
            for (var i = 0; i < arrayLength; i++) {
                var re = new RegExp('(' + word[i] + ')', "gi");
                $('#change').html($('#change').html().replace(re, '<span class="highlight">$1</span>'));
            }
        }
    });
</script>

<div class="row page-header">
    <div class="col-xs-12 col-sm-2 col-md-2 col-lg-4">
        <h2>
            Changes
        </h2>
    </div>
    {% if changes %}
    <div class="col-xs-12 col-sm-10 col-md-10 col-lg-8 text-right">
        <form class="form-inline search pull-right" action="{% url 'version:change-list' %}?page={{ current_page }}" method="get" accept-charset="utf-8">
            <div class="form-group" style="margin-bottom: 5px;">
                <input type="text" class="form-control search-form" id="q" name="q" value="{{ q }}" placeholder="Search changes">
                <button type="submit" class="btn btn-success">Search</button>
            </div>
            <div class="form-group">
                &emsp;
                <label>Date filter</label>
                <div class="input-group">
                    <input type="text" class="form-control filter-date-form datepicker" name="date_from" placeholder="From date" value="{{ date_from }}">
                    <div class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></div>
                </div>
                <div class="input-group">
                    <input type="text" class="form-control filter-date-form datepicker" name="date_to" placeholder="To date" value="{{ date_to }}">
                    <div class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></div>
                </div>
                <button type="submit" class="btn btn-success">Filter</button>
            </div>
        </form>
    </div>
    {% endif %}
</div>

{% if changes %}
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            {% if q %}
                <h4>Search results for: &emsp;<span class="text-success">"{{ q }}"</span></h4>
            {% endif %}
        </div>
        <div id="change" class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="table-responsive">
                <table class="table table-hover table-striped changes">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Date</th>
                            <th>Varsion</th>
                            {% if request.user.is_staff %}
                                <th>Client</th>
                                <th>Type</th>
                            {% endif %}
                            <th>Change</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for change in changes %}
                        <tr>
                            <td>{{ change.id }}</td>
                            <td>{{ change.date|date:"Y-m-d" }}</td>
                            <td>{{ change.version }}</td>
                            {% if request.user.is_staff %}
                                <td>{% if change.client %} {{ change.client }} {% else %}{% endif %}</td>
                                <td>{{ change.get_change_type_display }}</td>
                            {% endif %}
                            <td class="change-content">{{ change.description }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    {% if page_obj.has_other_pages %}
    <div class="row">
        <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
            <form class="form-inline pager pull-left" onsubmit="putCookie(this)">
                <div class="form-group">
                    <label>Items</label>
                    <input class="form-control" style="width: 5em;" id="paginated_by" name='paginated_by' type="number" min="1" value="{{ paginated_by }}">
                </div>
             </form>
        </div>
        <div class="col-xs-7 col-sm-7 col-md-7 col-lg-7 text-center">
            <form class="form-inline">
                <div class="form-group">
                    <ul class="pager">
                        <li><a href="?q={{ q }}&date_from={{ date_from }}&date_to={{ date_to }}&page=1"><span aria-hidden="true">&larr;</span> First</a></li>
                    </ul>
                </div>
                <div class="form-group">
                    <div class="text-center">
                        {% bootstrap_paginate page_obj range=10 %}
                    </div>
                </div>
                <div class="form-group">
                    <ul class="pager">
                    <li><a href="?q={{ q }}&date_from={{ date_from }}&date_to={{ date_to }}&page={{ page_obj.paginator.num_pages }}">Last <span aria-hidden="true">&rarr;</span></a></li>
                </ul>
                </div>
            </form>
        </div>
        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
            <form class="form-inline pager pull-right" action="{% url 'version:change-list' %}?q={{ q }}&page={{ page }}" method="get" accept-charset="utf-8">
                <div class="form-group">
                    <label>Page</label>
                    <input class="form-control" style="width: 6em;" type="number" min="1" max="{{ page_obj.paginator.num_pages }}" name="page" value="{{ page_obj.number }}">
                    <span><strong>/ {{ page_obj.paginator.num_pages }}</strong>&emsp;</span>
                    <button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-chevron-right"></i></button>
                </div>
             </form>
        </div>
    </div>
    {% endif %}
{% else %}
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 big_message_box">
            <h1>No changes</h1>
            {% if q or date_from or to_date %}
                <p>Go back to <a href="{% url 'version:change-list' %}">the changes page</a></p>
            {% else %}
                <p>Go to <a href="{% url 'version:version-list' %}">the main page</a></p>
            {% endif %}
        </div>
    </div>
{% endif %}

{% endblock content %}         

templates/version/contact.html
{% extends "base.html" %}
{% block content %}

<script type="text/javascript">
    $(document).ready(function() {
        $(".topic_version").show();
        $(".topic_change").hide();
        $(".topic_custom").hide();
    });
    $(function() {
        $("#topic").on("change",function() {
            if ($(this).val() === "Version") {
                $(".topic_version").show();
                $(".topic_change").hide();
                $(".topic_custom").hide();
            }
            if ($(this).val() === "Changes") {
                $(".topic_version").hide();
                $(".topic_change").show();
                $(".topic_custom").hide();
            }
            if ($(this).val() === "Other") {
                $(".topic_version").hide();
                $(".topic_change").hide();
                $(".topic_custom").show();
            }
        });
    });
</script>

<div class="row page-header">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <h2>
            Contact
        </h2>
    </div>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        {% if form.non_field_errors %}
            <div id="login-alert" class="alert alert-danger col-sm-12">
                {{ form.non_field_errors }}
            </div>
        {% endif %}
        <form class="contact" method="post" action="{% url 'version:contact' %}">
        {% csrf_token %}
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 form-group">
                <label class="col-sm-12 control-label">Topic</label>
                {{ form.topic }}
                <label class="col-sm-12 control-label topic_version">Choose version</label>
                {{ form.topic_version }}
                <label class="col-sm-12 control-label topic_change">Enter the change ID</label>
                {{ form.topic_change }}
                <label class="col-sm-12 control-label topic_custom">Other topic</label>
                {{ form.topic_custom }}
                {{ form.name }}
                {{ form.email }}
                {{ form.phone_number }}
            </div>
            <div class="col-sm-6 form-group">
                {{ form.message }}
            </div>
            <div class="col-sm-12 form-group text-center">
                <button type="submit" class="btn btn-success btn-lg">Submit</button>
            </div>
        </form>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-right">
            <small>* Required fields</small>
        </div>
    </div>
</div>

{% endblock content %}

templates/version/contact_done.html
{% extends "base.html" %}
{% block content %}

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 big_message_box">
        <h2>E-mail has been sent.</h2>
        <p>Go to <a href="{% url 'version:version-list' %}">the main page</a></p>
    </div>
</div>

{% endblock content %}

templates/version/contact_email.html
<p>Author:  <b>{{ name }}</b><br>
E-mail:  <b>{{ email }}</b><br>
Phone number:  <b>{{ phone_number }}</b><br>
Topic:  <b>{{ topic }}</b><br>
{% if topic_version %}
    Version:  <b>{{ topic_version }}</b><br>
{% endif %}
{% if topic_change %}
    Change ID:  <b>{{ topic_change }}</b><br>
{% endif %}
{% if topic_custom %}
    Topic content:  <b>{{ topic_custom }}</b><br>
{% endif %}
Message:<p>
<p>{{ message }}</p>