accounts/urls.py
from django.conf.urls import url
from .views import (
    # LoginView,
    # LogoutView,
    RegisterView,
    UserDetailView,
    UserListView,
    UserPasswordChangeView,
    UserPasswordChangeDoneView,
    UserPasswordResetView,
    UserPasswordResetDoneView,
    UserUpdateView,
)

urlpatterns = [
    # url(r'^login/$', LoginView.as_view(), name='login'),
    # url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^password_change/$', UserPasswordChangeView.as_view(), name='password-change'),
    url(r'^password-change/done/$', UserPasswordChangeDoneView.as_view(), name='password-change-done'),
    url(r'^password-reset/$', UserPasswordResetView.as_view(), name='password-reset'),
    url(r'^password-reset/done/$', UserPasswordResetDoneView.as_view(), name='password-reset-done'),
    url(r'^profile/$', UserDetailView.as_view(), name='user-detail'),
    url(r'^users/$', UserListView.as_view(), name='user-list'),
    url(r'^users/(?P<pk>\d+)/$', UserUpdateView.as_view(), name='user-update'),
]

version/urls.py
from django.conf.urls import url
from .views import (
    ContactView,
    ContactDoneView,
    file_download,
    ChangeList,
    VersionFilesView,
    VersionList,
)

urlpatterns = [
    url(r'^changes/$', ChangeList.as_view(), name='change-list'),
    url(r'^contact/$', ContactView.as_view(), name='contact'),
    url(r'^contact/done/$', ContactDoneView.as_view(), name='contact-done'),
    url(r'^file/(?P<pk>\d+)/$', file_download, name='file-download'),
    url(r'^version/$', VersionList.as_view(), name='version-list'),
    url(r'^version/files/(?P<pk>\d+)/$', VersionFilesView.as_view(), name='version-files'),
]

versionSystem/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic.base import RedirectView
import django.views.static

from accounts.views import (
    LoginView,
    LogoutView,
)


urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^', include('version.urls', namespace='version')),
    url(r'^$', RedirectView.as_view(url=reverse_lazy('version:version-list'), permanent=False)),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += [
        url(r'^static/(.*)$', django.views.static.serve, {'document_root': settings.STATIC_ROOT}),
        url(r'^media/(.*)$', django.views.static.serve, {'document_root': settings.MEDIA_ROOT}),
        url(r'^robots.txt', lambda x: HttpResponse("User-Agent: *\nDisallow: /", content_type="text/plain"), name="robots_file"),
    ]

accounts/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from django.conf import settings
from django.core.mail import send_mail
from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout,
)
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.utils.translation import ugettext_lazy as _
from version.models import Client


User = get_user_model()


# Admin Views


class AdminUserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField(label= ("Password"),
        help_text= ("<a href=\"../password/\">Change password</a>"))

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password', 'is_active', 'is_staff']

    def clean_password(self):
        return self.initial['password']


class AdminPasswordChangeForm(forms.Form):
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }
    password1 = forms.CharField(label=_("Password"),
                                widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Password (again)"),
                                widget=forms.PasswordInput)

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(AdminPasswordChangeForm, self).__init__(*args, **kwargs)

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(
                    self.error_messages['password_mismatch'])
        return password2

    def save(self, commit=True):
        self.user.set_password(self.cleaned_data["password1"])
        if commit:
            self.user.save()
        return self.user
        

# User Views


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'text',
            'placeholder': 'Login'})
        self.fields['password'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'password',
            'placeholder': 'Password'})

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
       
        if username and password:
            try:
                user_obj = User.objects.get(username=username)
            except:
                raise forms.ValidationError("User with this username does not exist.")
            if not user_obj.check_password(password):
                raise forms.ValidationError("You passed invalid password.")
            if not user_obj.is_active:
                raise forms.ValidationError("User is not active.")
        return super(UserLoginForm, self).clean(*args, **kwargs)


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)
    client = forms.ModelChoiceField(
        label = 'Client',
        queryset = Client.objects.all(),
        widget = forms.Select(attrs={
            'class':'form-control',
        }),
        required = False,
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'client']

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'text',
            'placeholder': 'Login *'})
        self.fields['password1'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'password',
            'placeholder': 'Password *'})
        self.fields['password2'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'password',
            'placeholder': 'Confirm password *'})
        self.fields['email'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'email',
            'placeholder': 'E-mail *'})
        self.fields['first_name'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'text',
            'placeholder': 'First name'})
        self.fields['last_name'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'text',
            'placeholder': 'Last name'})

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords must match.")
        return password2

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserUpdateForm(forms.ModelForm):
    client = forms.ModelChoiceField(
        label = 'Client',
        queryset = Client.objects.all(),
        widget = forms.Select(attrs={
            'class':'form-control',
        }),
        required = False,
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'is_active', 'client']

    def __init__(self, *args, **kwargs):
        super(UserUpdateForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'text',
            'placeholder': 'Login *'})
        self.fields['email'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'email',
            'placeholder': 'E-mail *'})
        self.fields['first_name'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'text',
            'placeholder': 'First name'})
        self.fields['last_name'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'text',
            'placeholder': 'Last name'})
        self.fields['is_active'].widget = forms.CheckboxInput(attrs={
            'class': 'checkbox',
            'type': 'checkbox'})


class PasswordChangeForm(forms.Form):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password1 = forms.CharField(label='New password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm new password', widget=forms.PasswordInput)

    def __init__(self, user, *args, **kwargs):
        super(PasswordChangeForm, self).__init__(*args, **kwargs)
        self.user = user
        self.fields['password'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'password',
            'placeholder': 'Password *'})
        self.fields['password1'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'password',
            'placeholder': 'New password *'})
        self.fields['password2'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'password',
            'placeholder': 'Confirm new password *'})

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if not self.user.check_password(password):
            raise forms.ValidationError("You passed invalid password.")
        return password

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords must match.")
        return password2

    def save(self, commit=True):
        password = self.cleaned_data.get('password1')
        self.user.set_password(password)
        if commit:
            self.user.save()
        return self.user


class PasswordResetForm(forms.Form):
    email = forms.EmailField()

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get("email")
        try:
            user = User.objects.get(email=email)
        except:
            raise forms.ValidationError("User with this email does not exist.") 
        return super(PasswordResetForm, self).clean(*args, **kwargs)

    def reset_password(self, email):
        user_obj = User.objects.get(email=email)
        password = User.objects.make_random_password()
        user_obj.set_password(password)
        user_obj.save()
        return password

    def send_email(self):
        user_email = self.cleaned_data['email']
        new_password = self.reset_password(user_email)

        user = User.objects.get(email=user_email)
        subject = "Your Version System account new password"
        message = "<p>Hi <b>%s</b>!<br>\
                   You have reset your password.\
                   Here is your new password: <b>%s</b><br>\
                   Now you can log in and change it\
                   in your profile.</p>\
                   <p>Thanks,\
                   <br>Version System administration</p>" % (
                    user.username, new_password
                   )
        from_email = settings.DEFAULT_FROM_EMAIL
        new_email = send_mail(
            subject,
            message,
            from_email,
            [user_email],
            html_message=message,
            fail_silently=False
        )
        return user_email

accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
    
from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout,
    update_session_auth_hash,
)
from django.contrib.auth.decorators import (
    login_required,
    permission_required,
)
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
    UserPassesTestMixin,
)
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
from django.views.generic import (
    FormView,
    ListView,
    RedirectView,
)
from django.views.generic.base import TemplateView
from django.views.generic.edit import UpdateView

from .forms import (
    PasswordChangeForm,
    PasswordResetForm,
    UserCreationForm,
    UserLoginForm,
    UserUpdateForm,
)


User = get_user_model()


class LoginView(FormView):
    form_class = UserLoginForm
    template_name = 'accounts/login.html'
    success_url = reverse_lazy('version:version-list')

    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return super(LoginView, self).form_valid(form)


class LogoutView(RedirectView):
    url = '/login/'
    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)


class RegisterView(LoginRequiredMixin, PermissionRequiredMixin, FormView):
    form_class = UserCreationForm
    template_name = 'accounts/register.html'
    success_url = reverse_lazy('accounts:user-list')
    permission_required = ['accounts.is_moderator']

    def form_valid(self, form):
        user = form.save(commit=False)
        if not self.request.user.is_staff:
            user.client = self.request.user.client
        password = form.cleaned_data.get('password1')
        user.set_password(password)
        user.save()
        return super(RegisterView, self).form_valid(form)

    def handle_no_permission(self):
        raise PermissionDenied


class UserDetailView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/user_detail.html'

    def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        context['user'] = User.objects.get(id=self.request.user.id)
        return context


class UserListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = User
    context_object_name = 'users'
    permission_required = ['accounts.is_moderator']

    def get_queryset(self):
        if self.request.user.is_staff:
            return User.objects.all()
        return User.objects.filter(client=self.request.user.client)

    def handle_no_permission(self):
        raise PermissionDenied


class UserPasswordChangeView(LoginRequiredMixin, FormView):
    form_class = PasswordChangeForm
    template_name = 'accounts/password-change.html'
    success_url = reverse_lazy('accounts:password-change-done')

    def get_form_kwargs(self):
        kwargs = super(UserPasswordChangeView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form): 
        form.save()
        update_session_auth_hash(self.request, form.user)
        return super(UserPasswordChangeView, self).form_valid(form)


class UserPasswordChangeDoneView(TemplateView):
    template_name = 'accounts/password-change-done.html'


class UserPasswordResetView(FormView):
    form_class = PasswordResetForm
    template_name = 'accounts/password-reset.html'
    success_url = reverse_lazy('accounts:password-reset-done')

    def form_valid(self, form):
        form.send_email()
        return super(UserPasswordResetView, self).form_valid(form)


class UserPasswordResetDoneView(TemplateView):
    template_name = 'accounts/password-reset-done.html'


class UserUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'accounts/user_update.html'
    success_url = reverse_lazy('accounts:user-list')
    permission_required = ['accounts.is_moderator']

    def test_func(self):
        pk = self.kwargs.get(self.pk_url_kwarg, None)
        if self.request.user.is_superuser:
            return True
        elif User.objects.get(id=pk).client is not None:
            return User.objects.get(id=pk).client.id == self.request.user.client.id
        else:
            return False

    def handle_no_permission(self):
        raise PermissionDenied

templates/accounts/login.html
{% extends "base.html" %}
{% block content %}

<div class="row page-header">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <h2>
            Log in
        </h2>
    </div>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-8 col-md-6 col-lg-4">
        <div class="panel-body login">
            {% if form.non_field_errors %}
                <div id="login-alert" class="alert alert-danger col-sm-12">
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
            <form id="loginform" class="form-horizontal" role="form" method="post" action="{% url 'login' %}">
            {% csrf_token %}
                <div class="input-group form">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                    {{ form.username }}
                </div>
                <span class="text-danger">{{ form.username.errors }}</span>
                <div class="input-group form">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                    {{ form.password }}
                </div>
                <span class="text-danger">{{ form.password.errors }}</span>
                <div class="form-group button">
                    <div class="col-sm-12 controls">
                      <button id="btn-login" type="submit" class="btn btn-success">Login</button>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12 text-right">
                        <small>Forgot password? <a href='{% url "accounts:password-reset" %}'>Reset password here</a>.</small>
                    </div>
                </div>
            </form>
        </div>
    </div>  
</div>

{% endblock content %}

templates/accounts/password-change-done.html
{% extends "base.html" %}
{% block content %}

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 big_message_box">
        <h2>Password has been successfully updated.</h2>
        <p>Go to <a href="{% url 'version:version-list' %}">the main page</a></p>
    </div>
</div>

{% endblock content %}

templates/accounts/password-change.html
{% extends "base.html" %}
{% block content %}

<div class="row page-header">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <h2>
            Password Change
        </h2>
    </div>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-8 col-md-6 col-lg-4">
        <div class="panel-body login">
            {% if form.non_field_errors %}
                <div id="login-alert" class="alert alert-danger col-sm-12">
                    The change password operation failed. Please try again.
                </div>
            {% endif %}
            <form id="password-change" class="form-horizontal" role="form" method="post" action="{% url 'accounts:password-change' %}">
            {% csrf_token %}
                <div class="input-group form">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                    {{ form.password }}
                </div>
                <span class="text-danger">{{ form.password.errors }}</span>
                <div class="input-group form">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                    {{ form.password1 }}
                </div>
                <span class="text-danger">{{ form.password1.errors }}</span>
                <div class="input-group form">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                    {{ form.password2 }}
                </div>
                <span class="text-danger">{{ form.password2.errors }}</span>
                <div class="form-group button">
                    <div class="col-sm-12 controls">
                        <input type="submit" class="btn btn-success" value="Change">
                        <a id="btn-cancel" href="{% url 'version:version-list' %}" class="btn btn-warning">Cancel</a>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12 text-right">
                        <small>* Required fields</small>
                    </div>
                </div>
            </form>
        </div>                     
    </div>  
</div>

{% endblock content %}

templates/accounts/register.html
{% extends "base.html" %}
{% block content %}

<div class="row page-header">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <h2>
            Registration
        </h2>
    </div>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-10 col-md-8 col-lg-4">
        <div class="panel-body login">
        {% if form.non_field_errors %}
            <div id="login-alert" class="alert alert-danger col-sm-12">
                {{ form.non_field_errors }}
            </div>
        {% endif %}
            <form id="loginform" class="form-horizontal" role="form" method="post" action="{% url 'accounts:register' %}">
            {% csrf_token %}
                <div class="input-group form">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                    {{ form.username }}
                </div>
                <span class="text-danger">{{ form.username.errors }}</span>
                <div class="input-group form">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                    {{ form.password1 }}
                </div>
                <span class="text-danger">{{ form.password1.errors }}</span>
                <div class="input-group form">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                    {{ form.password2 }}
                </div>
                <span class="text-danger">{{ form.password2.errors }}</span>
                <div class="input-group form">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                    {{ form.email }}
                </div>
                <span class="text-danger">{{ form.email.errors }}</span>
                <div class="input-group form">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                    {{ form.first_name }}
                </div>
                <span class="text-danger">{{ form.first_name.errors }}</span>
                <div class="input-group form">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                    {{ form.last_name }}
                </div>

                {% if request.user.is_staff %}
                <span class="text-danger">{{ form.client.errors }}</span>
                <div class="form-group form">
                    <label class="col-sm-2 control-label">Client</label>
                    <div class="col-sm-10">
                        {{ form.client }}
                    </div>
                </div>
                {% endif %}

                <span class="text-danger">{{ form.last_name.errors }}</span>
                <div class="form-group button">
                    <div class="col-sm-12 controls">
                      <input type="submit" id="btn-login" class="btn btn-success" value="Register">
                      <a id="btn-cancel" href="{% url 'accounts:user-list' %}" class="btn btn-warning">Cancel</a>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12 text-right">
                        <small>* Required fields</small>
                    </div>
                </div>
            </form>
        </div>
    </div>  
</div>

{% endblock content %}

templates/accounts/user_list.html
{% extends "base.html" %}
{% block content %}

<div class="row page-header">
   <div class="col-xs-6 col-sm-6 col-md-2 col-lg-2">
        <h2>
            Users
        </h2>
    </div>
    <div class="col-xs-6 col-sm-6 col-md-10 col-lg-10 text-right">
        <h2>
            <a href="{% url 'accounts:register' %}" type="button" class="btn btn-primary btn-lg">Create User</a>
        </h2>
    </div>
</div>

{% if users %}
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="table-responsive">
            <table class="table table-hover table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Last name</th>
                        <th>First name</th>
                        <th>Login</th>
                        <th>E-mail</th>
                        {% if request.user.is_staff %}
                            <th>Client</th>
                        {% endif %}
                        <th>Date joined</th>
                        <th>Last login</th>
                        <th>Active</th>
                        <th>Edit</th>
                    </tr>
                </thead>
                <tbody>
                {% for user in users|dictsort:"last_name" %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ user.last_name }}</td>
                        <td>{{ user.first_name }}</td>
                        <td>{{ user.username }}</td>
                        <td>{{ user.email }}</td>
                        {% if request.user.is_staff %}
                            <td>{% if user.client %} {{ user.client }} {% else %}{% endif %}</td>
                        {% endif %}
                        <td>{{ user.date_joined }}</td>
                        <td>{% if user.last_login %}{{ user.last_login }}{% endif %}</td>
                        {% if user.is_active %}
                            <td><span class="glyphicon glyphicon-ok text-success"></span></td>
                        {% else %}
                            <td><span class="glyphicon glyphicon-remove text-danger"></span></td>
                        {% endif %}
                        <td><a href="{% url 'accounts:user-update' user.id %}"><span class="glyphicon glyphicon-pencil"></span></a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% else %}
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 big_message_box">
        <h1>No Users</h1>
        <p>Go to <a href="{% url 'version:version-list' %}">the main page</a></p>
    </div>
</div>
{% endif %}

{% endblock content %}

templates/accounts/user_update.html
{% extends "base.html" %}
{% block content %}

<div class="row page-header">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <h2>
            Edit user: &emsp;<span class="text-success">{{ user.username }}</span>
        </h2>
    </div>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-11 col-md-8 col-lg-4">
        {% if form.non_field_errors %}
            <div id="login-alert" class="alert alert-danger col-sm-12">
                {{ form.non_field_errors }}
            </div>
        {% endif %}
        <form class="form-horizontal" method="post" action="{% url 'accounts:user-update' user.id %}">
        {% csrf_token %}
            <div class="form-group">
                <label class="col-sm-2 control-label">Login*</label>
                <div class="col-sm-10">
                    {{ form.username }}
                    <span class="text-danger">{{ form.username.errors }}</span>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">E-mail*</label>
                <div class="col-sm-10">
                    {{ form.email }}
                    <span class="text-danger">{{ form.email.errors }}</span>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">First name</label>
                <div class="col-sm-10">
                    {{ form.first_name }}
                    <span class="text-danger">{{ form.first_name.errors }}</span>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Last name</label>
                <div class="col-sm-10">
                    {{ form.last_name }}
                    <span class="text-danger">{{ form.last_name.errors }}</span>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Active</label>
                <div class="col-sm-10">
                    {{ form.is_active }}
                    <span class="text-danger">{{ form.is_active.errors }}</span>
                </div>
            </div>

            {% if request.user.is_staff %}
            <div class="form-group">
                <label class="col-sm-2 control-label">Client</label>
                <div class="col-sm-10">
                    {{ form.client }}
                </div>
            </div>
            {% endif %}
            
            <div class="form-group button">
                <label class="col-sm-3 control-label"></label>
                <div class="col-sm-10 controls">
                    <input type="submit" id="btn-edit" class="btn btn-success" value="Edit">
                    <a id="btn-cancel" href="{% url 'accounts:user-list' %}" class="btn btn-warning">Cancel</a>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-12 control text-right">
                    <small>* Pola obowiązkowe</small>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock content %}