accounts/urls.py
from django.conf.urls import url
from .views import (
    # LoginView,
    # LogoutView,
    RegisterView,
    UserDetailView,
    UserListView,
    UserPasswordChangeView,
    UserPasswordChangeDoneView,
    UserPasswordResetView,
    UserPasswordResetDoneView,
    UserUpdateView,
)

urlpatterns = [
    # url(r'^login/$', LoginView.as_view(), name='login'),
    # url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^password_change/$', UserPasswordChangeView.as_view(), name='password-change'),
    url(r'^password-change/done/$', UserPasswordChangeDoneView.as_view(), name='password-change-done'),
    url(r'^password-reset/$', UserPasswordResetView.as_view(), name='password-reset'),
    url(r'^password-reset/done/$', UserPasswordResetDoneView.as_view(), name='password-reset-done'),
    url(r'^profile/$', UserDetailView.as_view(), name='user-detail'),
    url(r'^users/$', UserListView.as_view(), name='user-list'),
    url(r'^users/(?P<pk>\d+)/$', UserUpdateView.as_view(), name='user-update'),
]

version/urls.py
from django.conf.urls import url
from .views import (
    ContactView,
    ContactDoneView,
    file_download,
    ChangeList,
    VersionFilesView,
    VersionList,
)

urlpatterns = [
    url(r'^changes/$', ChangeList.as_view(), name='change-list'),
    url(r'^contact/$', ContactView.as_view(), name='contact'),
    url(r'^contact/done/$', ContactDoneView.as_view(), name='contact-done'),
    url(r'^file/(?P<pk>\d+)/$', file_download, name='file-download'),
    url(r'^version/$', VersionList.as_view(), name='version-list'),
    url(r'^version/files/(?P<pk>\d+)/$', VersionFilesView.as_view(), name='version-files'),
]

versionSystem/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic.base import RedirectView
import django.views.static

from accounts.views import (
    LoginView,
    LogoutView,
)


urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^', include('version.urls', namespace='version')),
    url(r'^$', RedirectView.as_view(url=reverse_lazy('version:version-list'), permanent=False)),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += [
        url(r'^static/(.*)$', django.views.static.serve, {'document_root': settings.STATIC_ROOT}),
        url(r'^media/(.*)$', django.views.static.serve, {'document_root': settings.MEDIA_ROOT}),
        url(r'^robots.txt', lambda x: HttpResponse("User-Agent: *\nDisallow: /", content_type="text/plain"), name="robots_file"),
    ]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Version System">
    <meta name="author" content="Krystian Kasperski">
    <meta name="robots" content="noindex">
    <meta name="googlebot" content="noindex">
    
    <title>{% block head_title %}Version System{% endblock head_title %}</title>

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" rel="stylesheet">
    <link href="http://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" rel="stylesheet" >
    <link href='{% static "css/style.css" %}' rel="stylesheet">

    <script src="http://code.jquery.com/jquery-1.12.4.min.js"
            integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
            crossorigin="anonymous"></script>

    <script src="http://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
            integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
            crossorigin="anonymous"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" 
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% block head_extra %} {% endblock head_extra %}
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-left">
        <div class="logo">
            <a class="navbar-brand" href="{% url 'version:version-list' %}"><img src='{% static "img/version-system.png" %}' width="157" height="50" alt="Version System"></a>
        </div>
        <ul class="nav navbar-nav">
        {% if not request.user.is_authenticated %}
            <li>
                <a href="{% url 'login' %}"><i class="glyphicon glyphicon-user"></i> Log in</a>
            </li>
            <li>
                <a href="{% url 'version:contact' %}"><i class="glyphicon glyphicon-envelope"></i> Contact</a>
            </li>
        {% else %}
            {% if perms.accounts.is_moderator %}
            <li>
                <a href="{% url 'accounts:user-list' %}"><i class="glyphicon glyphicon-user"></i> Users</a>
            </li>
            {% endif %}
            <li>
                <a href="{% url 'version:version-list' %}"><i class="glyphicon glyphicon-file"></i> Versions</a>
            </li>
            <li>
                <a href="{% url 'version:change-list' %}"><i class="glyphicon glyphicon-retweet"></i> Changes</a>
            </li>
            <li>
                <a href="{% url 'version:contact' %}"><i class="glyphicon glyphicon-envelope"></i> Contact</a>
            </li>
            <li>
                <a href="{% url 'accounts:user-detail' %}"><i class="glyphicon glyphicon-user"></i> Profile</a>
            </li>
            <li>
                <a href="{% url 'logout' %}"><i class="glyphicon glyphicon-off"></i> Log out [ <strong>{{ request.user.username }}</strong> ]</a>
            </li>
        {% endif %}
        </ul>
    </div>

    <div class="container">
        <div class="row">
            
            {% block content %}{% endblock content %}

        </div>
    </div>

</body>
</html>